"""new tabels for agent b

Revision ID: 88485d2f1c74
Revises: add_processed_event_updated_at
Create Date: 2026-04-06 15:37:58.881058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88485d2f1c74'
down_revision: Union[str, Sequence[str], None] = 'add_processed_event_updated_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entities_verified'), 'entities', ['verified'], unique=False)
    op.create_index('ix_entity_wallets', 'entities', ['wallets'], unique=False)
    op.alter_column('processed_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_processed_events_updated_at'), table_name='processed_events')
    op.create_index('ix_is_profitable', 'trade_records', ['is_profitable'], unique=False)
    op.drop_constraint(op.f('wallet_profiles_address_key'), 'wallet_profiles', type_='unique')
    op.drop_index(op.f('ix_wallet_profiles_address'), table_name='wallet_profiles')
    op.create_index(op.f('ix_wallet_profiles_address'), 'wallet_profiles', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_profiles_address'), table_name='wallet_profiles')
    op.create_index(op.f('ix_wallet_profiles_address'), 'wallet_profiles', ['address'], unique=False)
    op.create_unique_constraint(op.f('wallet_profiles_address_key'), 'wallet_profiles', ['address'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_is_profitable', table_name='trade_records')
    op.create_index(op.f('ix_processed_events_updated_at'), 'processed_events', ['updated_at'], unique=False)
    op.alter_column('processed_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_entity_wallets', table_name='entities')
    op.drop_index(op.f('ix_entities_verified'), table_name='entities')
    # ### end Alembic commands ###
