"""Process Events Table and alerts table

Revision ID: 99627ce2eeb8
Revises: b277df263020
Create Date: 2026-03-01 15:19:20.462077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "99627ce2eeb8"
down_revision: Union[str, Sequence[str], None] = "b277df263020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("multi_source", sa.Integer(), nullable=True),
        sa.Column("engagement", sa.Integer(), nullable=True),
        sa.Column("bot", sa.Integer(), nullable=True),
        sa.Column("dedup", sa.Integer(), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_priority_timestamp_user",
        "processed_events",
        ["priority", "timestamp", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_events_priority"),
        "processed_events",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_events_timestamp"),
        "processed_events",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_events_user_id"),
        "processed_events",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_events_user_id"), table_name="processed_events")
    op.drop_index(op.f("ix_processed_events_timestamp"), table_name="processed_events")
    op.drop_index(op.f("ix_processed_events_priority"), table_name="processed_events")
    op.drop_index("ix_priority_timestamp_user", table_name="processed_events")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
